package jarnal;

import javax.swing.*;

public class Images {
    static ImageIcon hand;
    static ImageIcon handstop;
    static ImageIcon handyellow;
    static ImageIcon handmixed;
    static ImageIcon handmixed2;
    static ImageIcon fsave;
    static ImageIcon newdoc;
    static ImageIcon undo;
    static ImageIcon redo;
    static ImageIcon minus;
    static ImageIcon plus;
    static ImageIcon fit;
    static ImageIcon eraser;
    static ImageIcon erasetop;
    static ImageIcon erasebot;
    static ImageIcon bigeraser;
    static ImageIcon clonedoc;
    static ImageIcon red;
    static ImageIcon blk;
    static ImageIcon blu;
    static ImageIcon mgn;
    static ImageIcon grn;
    static ImageIcon highyel;
    static ImageIcon highmag;
    static ImageIcon highdef;
    static ImageIcon white;
    static ImageIcon left;
    static ImageIcon leftleft;
    static ImageIcon right;
    static ImageIcon rightright;
    static ImageIcon select;
    static ImageIcon selectrect;
    static ImageIcon newpage;
    static ImageIcon def;
    static ImageIcon fin;
    static ImageIcon med;
    static ImageIcon hev;
    static ImageIcon fat;
    static ImageIcon razor;
    static ImageIcon ruler;
    static ImageIcon thumbsico;
    static ImageIcon opico;
    static ImageIcon text;
    static ImageIcon clock;
    static ImageIcon threePages;
    static ImageIcon editcut;
    static ImageIcon editcopy;
    static ImageIcon editpaste;
    static ImageIcon cap;
    static ImageIcon num;
    static ImageIcon sym;
    static ImageIcon calc;
    static ImageIcon LC;
    static ImageIcon Spc;
    static ImageIcon Bsp;
    static ImageIcon browse;
    static ImageIcon fullscreen;
    static ImageIcon returnico;
    static ImageIcon userico;
    static ImageIcon multi;
    static ImageIcon iwidth;
    static ImageIcon wrench;
    static ImageIcon arrow;
    static ImageIcon jarnalIcon;

    public static void loadImagesLarge() {
        fsave      = new ImageIcon(Jarnal.class.getResource("images/filesave-l.png"));
        newdoc     = new ImageIcon(Jarnal.class.getResource("images/newdoc-l.png"));
        undo       = new ImageIcon(Jarnal.class.getResource("images/undo-l.png"));
        redo       = new ImageIcon(Jarnal.class.getResource("images/redo-l.png"));
        minus      = new ImageIcon(Jarnal.class.getResource("images/viewmag--l.png"));
        plus       = new ImageIcon(Jarnal.class.getResource("images/viewmag+-l.png"));
        fit        = new ImageIcon(Jarnal.class.getResource("images/viewmagfit-l.png"));
        eraser     = new ImageIcon(Jarnal.class.getResource("images/eraser-l.png"));
        erasetop   = new ImageIcon(Jarnal.class.getResource("images/erasetop-l.png"));
        erasebot   = new ImageIcon(Jarnal.class.getResource("images/erasebot-l.png"));
        bigeraser  = new ImageIcon(Jarnal.class.getResource("images/bigeraser-l.png"));
        clonedoc   = new ImageIcon(Jarnal.class.getResource("images/clonedoc-l.png"));
        red        = new ImageIcon(Jarnal.class.getResource("images/pencilred-l.png"));
        blk        = new ImageIcon(Jarnal.class.getResource("images/pencilblk-l.png"));
        blu        = new ImageIcon(Jarnal.class.getResource("images/pencilblu-l.png"));
        grn        = new ImageIcon(Jarnal.class.getResource("images/pencilgrn-l.png"));
        mgn        = new ImageIcon(Jarnal.class.getResource("images/pencilmgn-l.png"));
        highyel    = new ImageIcon(Jarnal.class.getResource("images/highlighteryel-l.png"));
        highmag    = new ImageIcon(Jarnal.class.getResource("images/highlightermag-l.png"));
        highdef    = new ImageIcon(Jarnal.class.getResource("images/highlighterdef-l.png"));
        white      = new ImageIcon(Jarnal.class.getResource("images/whiteout-l.png"));
        left       = new ImageIcon(Jarnal.class.getResource("images/1leftarrow-l.png"));
        leftleft   = new ImageIcon(Jarnal.class.getResource("images/2leftarrow-l.png"));
        right      = new ImageIcon(Jarnal.class.getResource("images/1rightarrow-l.png"));
        rightright = new ImageIcon(Jarnal.class.getResource("images/2rightarrow-l.png"));
        select     = new ImageIcon(Jarnal.class.getResource("images/select-l.png"));
        selectrect = new ImageIcon(Jarnal.class.getResource("images/selectrect-l.png"));
        newpage    = new ImageIcon(Jarnal.class.getResource("images/new-l.png"));
        def        = new ImageIcon(Jarnal.class.getResource("images/default-l.png"));
        fin        = new ImageIcon(Jarnal.class.getResource("images/fine-l.png"));
        med        = new ImageIcon(Jarnal.class.getResource("images/medium-l.png"));
        hev        = new ImageIcon(Jarnal.class.getResource("images/heavy-l.png"));
        fat        = new ImageIcon(Jarnal.class.getResource("images/fat-l.png"));
        razor      = new ImageIcon(Jarnal.class.getResource("images/razor-l.png"));
        ruler      = new ImageIcon(Jarnal.class.getResource("images/ruler-l.png"));
        thumbsico  = new ImageIcon(Jarnal.class.getResource("images/thumbs-l.png"));
        opico      = new ImageIcon(Jarnal.class.getResource("images/opico-l.png"));
        threePages = new ImageIcon(Jarnal.class.getResource("images/threepages-l.png"));
        text       = new ImageIcon(Jarnal.class.getResource("images/text-l.png"));
        clock      = new ImageIcon(Jarnal.class.getResource("images/clock-l.png"));
        hand       = new ImageIcon(Jarnal.class.getResource("images/hand-l.png"));
        handstop   = new ImageIcon(Jarnal.class.getResource("images/handstop-l.png"));
        handyellow = new ImageIcon(Jarnal.class.getResource("images/handyellow-l.png"));
        handmixed  = new ImageIcon(Jarnal.class.getResource("images/handmixed-l.png"));
        handmixed2 = new ImageIcon(Jarnal.class.getResource("images/handmixed2-l.png"));
        editcut    = new ImageIcon(Jarnal.class.getResource("images/editcut-l.png"));
        editcopy   = new ImageIcon(Jarnal.class.getResource("images/editcopy-l.png"));
        editpaste  = new ImageIcon(Jarnal.class.getResource("images/editpaste-l.png"));
        cap        = new ImageIcon(Jarnal.class.getResource("images/cap-l.png"));
        num        = new ImageIcon(Jarnal.class.getResource("images/num-l.png"));
        sym        = new ImageIcon(Jarnal.class.getResource("images/sym-l.png"));
        calc       = new ImageIcon(Jarnal.class.getResource("images/calc-l.png"));
        LC         = new ImageIcon(Jarnal.class.getResource("images/lc-l.png"));
        Spc        = new ImageIcon(Jarnal.class.getResource("images/spc-l.png"));
        Bsp        = new ImageIcon(Jarnal.class.getResource("images/bsp-l.png"));
        browse     = new ImageIcon(Jarnal.class.getResource("images/browser-l.png"));
        fullscreen = new ImageIcon(Jarnal.class.getResource("images/fullscreen-l.png"));
        returnico  = new ImageIcon(Jarnal.class.getResource("images/rtn-l.png"));
        userico    = new ImageIcon(Jarnal.class.getResource("images/user-l.png"));
        multi      = new ImageIcon(Jarnal.class.getResource("images/multi-l.png"));
        iwidth     = new ImageIcon(Jarnal.class.getResource("images/iwidth-l.png"));
        wrench     = new ImageIcon(Jarnal.class.getResource("images/wrench-l.png"));
        arrow      = new ImageIcon(Jarnal.class.getResource("images/arrow-l.png"));
        jarnalIcon = new ImageIcon(Jarnal.class.getResource("images/jarnal.png"));
    }

    public static void loadImages() {
        fsave      = new ImageIcon(Jarnal.class.getResource("images/filesave.png"));
        newdoc     = new ImageIcon(Jarnal.class.getResource("images/newdoc.png"));
        undo       = new ImageIcon(Jarnal.class.getResource("images/undo.png"));
        redo       = new ImageIcon(Jarnal.class.getResource("images/redo.png"));
        minus      = new ImageIcon(Jarnal.class.getResource("images/viewmag-.png"));
        plus       = new ImageIcon(Jarnal.class.getResource("images/viewmag+.png"));
        fit        = new ImageIcon(Jarnal.class.getResource("images/viewmagfit.png"));
        eraser     = new ImageIcon(Jarnal.class.getResource("images/eraser.png"));
        erasetop   = new ImageIcon(Jarnal.class.getResource("images/erasetop.png"));
        erasebot   = new ImageIcon(Jarnal.class.getResource("images/erasebot.png"));
        bigeraser  = new ImageIcon(Jarnal.class.getResource("images/bigeraser.png"));
        clonedoc   = new ImageIcon(Jarnal.class.getResource("images/clonedoc.png"));
        red        = new ImageIcon(Jarnal.class.getResource("images/pencilred.png"));
        blk        = new ImageIcon(Jarnal.class.getResource("images/pencilblk.png"));
        blu        = new ImageIcon(Jarnal.class.getResource("images/pencilblu.png"));
        grn        = new ImageIcon(Jarnal.class.getResource("images/pencilgrn.png"));
        mgn        = new ImageIcon(Jarnal.class.getResource("images/pencilmgn.png"));
        highyel    = new ImageIcon(Jarnal.class.getResource("images/highlighteryel.png"));
        highmag    = new ImageIcon(Jarnal.class.getResource("images/highlightermag.png"));
        highdef    = new ImageIcon(Jarnal.class.getResource("images/highlighterdef.png"));
        white      = new ImageIcon(Jarnal.class.getResource("images/whiteout.png"));
        left       = new ImageIcon(Jarnal.class.getResource("images/1leftarrow.png"));
        leftleft   = new ImageIcon(Jarnal.class.getResource("images/2leftarrow.png"));
        right      = new ImageIcon(Jarnal.class.getResource("images/1rightarrow.png"));
        rightright = new ImageIcon(Jarnal.class.getResource("images/2rightarrow.png"));
        select     = new ImageIcon(Jarnal.class.getResource("images/select.png"));
        selectrect = new ImageIcon(Jarnal.class.getResource("images/selectrect.png"));
        newpage    = new ImageIcon(Jarnal.class.getResource("images/new.png"));
        def        = new ImageIcon(Jarnal.class.getResource("images/default.png"));
        fin        = new ImageIcon(Jarnal.class.getResource("images/fine.png"));
        med        = new ImageIcon(Jarnal.class.getResource("images/medium.png"));
        hev        = new ImageIcon(Jarnal.class.getResource("images/heavy.png"));
        fat        = new ImageIcon(Jarnal.class.getResource("images/fat.png"));
        razor      = new ImageIcon(Jarnal.class.getResource("images/razor.png"));
        ruler      = new ImageIcon(Jarnal.class.getResource("images/ruler.png"));
        thumbsico  = new ImageIcon(Jarnal.class.getResource("images/thumbs.png"));
        opico      = new ImageIcon(Jarnal.class.getResource("images/opico.png"));
        threePages = new ImageIcon(Jarnal.class.getResource("images/threepages.png"));
        text       = new ImageIcon(Jarnal.class.getResource("images/text.png"));
        clock      = new ImageIcon(Jarnal.class.getResource("images/clock.png"));
        hand       = new ImageIcon(Jarnal.class.getResource("images/hand.png"));
        handstop   = new ImageIcon(Jarnal.class.getResource("images/handstop.png"));
        handyellow = new ImageIcon(Jarnal.class.getResource("images/handyellow.png"));
        handmixed  = new ImageIcon(Jarnal.class.getResource("images/handmixed.png"));
        handmixed2 = new ImageIcon(Jarnal.class.getResource("images/handmixed2.png"));
        editcut    = new ImageIcon(Jarnal.class.getResource("images/editcut.png"));
        editcopy   = new ImageIcon(Jarnal.class.getResource("images/editcopy.png"));
        editpaste  = new ImageIcon(Jarnal.class.getResource("images/editpaste.png"));
        cap        = new ImageIcon(Jarnal.class.getResource("images/cap.png"));
        num        = new ImageIcon(Jarnal.class.getResource("images/num.png"));
        sym        = new ImageIcon(Jarnal.class.getResource("images/sym.png"));
        calc       = new ImageIcon(Jarnal.class.getResource("images/calc.png"));
        LC         = new ImageIcon(Jarnal.class.getResource("images/lc.png"));
        Spc        = new ImageIcon(Jarnal.class.getResource("images/spc.png"));
        Bsp        = new ImageIcon(Jarnal.class.getResource("images/bsp.png"));
        browse     = new ImageIcon(Jarnal.class.getResource("images/browser.png"));
        fullscreen = new ImageIcon(Jarnal.class.getResource("images/fullscreen.png"));
        returnico  = new ImageIcon(Jarnal.class.getResource("images/rtn.png"));
        userico    = new ImageIcon(Jarnal.class.getResource("images/user.png"));
        multi      = new ImageIcon(Jarnal.class.getResource("images/multi.png"));
        iwidth     = new ImageIcon(Jarnal.class.getResource("images/iwidth.png"));
        wrench     = new ImageIcon(Jarnal.class.getResource("images/wrench.png"));
        arrow      = new ImageIcon(Jarnal.class.getResource("images/arrow.png"));
        jarnalIcon = new ImageIcon(Jarnal.class.getResource("images/jarnal.png"));
    }

}
